eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      --defaultZone: http://192.168.0.239:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
status:
 messages: 
   succesful: OK
   unsuccesful: Error Unknown.
   noresult: No se encontraron resultados
 codes: {succesful: '0', unsuccesful: '1', noresult: '2', request_required: '3'}

